export const OPEN_SIDEBAR = "OPEN_SIDEBAR";
export const CLOSE_SIDEBAR = "CLOSE_SIDEBAR";
export const HISTORY_CLICK = "HISTORY_CLICK";
export const ACCOUNT_SETTING_CLICK = "ACCOUNT_SETTING_CLICK";
export const OPEN_FEEDBACK = "OPEN_FEEDBACK";
export const CLOSE_FEEDBACK = "CLOSE_FEEDBACK";

// category

export const FETCH_CATEGORY = "FETCH_CATEGORY";
export const CATEGORY_LOADING = "CATEGORY_LOADING";
export const CATEGORY_COMPLETE_LOADING = "CATEGORY_COMPLETE_LOADING";
export const CATEGORY_EXIST = "CATEGORY_EXIST";
export const SET_CATEGORY_ID = "SET_CATEGORY_ID";

// product

export const NEW_ARRIVAL_SET_LOADING = "NEW_ARRIVAL_SET_LOADING";
export const NEW_ARRIVAL_SET_ERROR = "NEW_ARRIVAL_SET_ERROR";
export const NEW_ARRIVAL_SET_PRODUCT = "NEW_ARRIVAL_SET_PRODUCT";
export const SET_LOADING_ALL_FAVOR_BOOK = "SET_LOADING_ALL_FAVOR_BOOK";
export const SET_ERROR_ALL_FAVOR_BOOK = "SET_ERROR_ALL_FAVOR_BOOK";
export const SET_PRODUCT_ALL_FAVOR_BOOK = "SET_PRODUCT_ALL_FAVOR_BOOK";
export const SET_NEW_ARRIVAL_PAGE = "SET_NEW_ARRIVAL_PAGE";

// single product

export const SET_SINGLE_PRODUCT_LOADING = "SET_SINGLE_PRODUCT_LOADING";
export const SET_SINGLE_PRODUCT_ERROR = "SET_SINGLE_PRODUCT_ERROR";
export const SET_SINGLE_PRODUCT = "SET_SINGLE_PRODUCT";