export const OPEN_SIDEBAR = "OPEN_SIDEBAR";
export const CLOSE_SIDEBAR = "CLOSE_SIDEBAR";
export const HISTORY_CLICK = "HISTORY_CLICK";
export const ACCOUNT_SETTING_CLICK = "ACCOUNT_SETTING_CLICK";
export const OPEN_FEEDBACK = "OPEN_FEEDBACK";
export const CLOSE_FEEDBACK = "CLOSE_FEEDBACK";